version: '3'
services:
  database:
    image: postgres:16.0-alpine
    ports:
      - 5441:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080
